const Perfumes = [
  {
    _id: "1",
    name: "Cerejeira Perfume",
    image: "/images/cerejeira-perfume.jpg",
    description: "Un perfume fresco y floral con notas de cereza.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Flor Rosa Perfume",
    image: "/images/flor-rosa-perfume.jpg",
    description: "Un aroma suave y romántico que evoca un jardín en flor.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 159.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Lírio Perfume",
    image: "/images/lirio-perfume.jpg",
    description: "Perfume con notas de lirio que ofrece una fragancia sofisticada.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 229.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 17,
  },
  {
    _id: "4",
    name: "Mar Perfume",
    image: "/images/mar-perfume.jpg",
    description: "Fragancia fresca y acuática que recuerda al océano.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 249.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Orquídea Perfume",
    image: "/images/orquidea-perfume.jpg",
    description: "Un perfume exótico y floral que captura la esencia de la orquídea.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 249.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Tulipe Perfume",
    image: "/images/tulipe-perfume.jpg",
    description: "Perfume clásico con un toque moderno, ideal para el uso diario.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 199.99,
    countInStock: 12,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: "7",
    name: "Jasmin Perfume",
    image: "/images/jasmin-perfume.jpg",
    description: "Aroma dulce y seductor con notas de jazmín.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 180.00,
    countInStock: 12,
    rating: 4.5,
    numReviews: 11,
  },
  {
    _id: "8",
    name: "Mulher Perfume",
    image: "/images/perfume-feminino.jpg",
    description: "Fragancia femenina y elegante para cualquier ocasión.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 160.00,
    countInStock: 20,
    rating: 4,
    numReviews: 14,
  },
  {
    _id: "9",
    name: "Capim-dos-Pampas Perfume",
    image: "/images/capim-dos-pampas-perfume.jpg",
    description: "Una fragancia única que evoca la frescura de la naturaleza.",
    brand: "Tulipe",
    category: "Natural Perfume",
    price: 200.00,
    countInStock: 0, // Agregar lógica para indicar que está fuera de stock
    rating: 4,
    numReviews: 16,
  },
];

export default Perfumes;

